services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/playlist?authSource=admin"
    depends_on: [mongo]
    env_file:
      - .env
    volumes:
      - ./app:/app

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
