apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080 # puerto interno que el pod expone
      targetPort: 8080 # puerto dentro del contenedor
