apiVersion: v1
kind: Service
metadata:
  name: playlist-api
  labels:
    app: playlist-api
spec:
  type: ClusterIP
  selector:
    app: playlist-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
