apiVersion: v1
kind: Service
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  type: ClusterIP
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002