apiVersion: apps/v1
kind: Deployment
metadata:
  name: artist-db
  labels:
    app: artist-db
spec:
  selector:
    matchLabels:
      app: artist-db
  template:
    metadata:
      labels:
        app: artist-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: artist-db-secret
                  key: DB_PASS
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: artist-db-secret
                  key: DB_NAME
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: artist-db-pvc