services:
  users-db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pginit:/docker-entrypoint-initdb.d

  users-service:
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "users-db"
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    depends_on:
      - users-db
