services:
  users-db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pginit:/docker-entrypoint-initdb.d
      - ./app:/app
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    volumes:
      - ./keycloak_data:/opt/keycloak/data/h2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${KEYCLOAK_PORT:-8080}/"]
      interval: 10s
      timeout: 10s
      retries: 10

  users-service:
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "users-db"
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    depends_on:
      - users-db
      - keycloak
